modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="sonic_craft_generations"
version="1.0.0"
displayName="Sonic Craft: Generations"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="J, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sonic_craft_generations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration